theory Cypher
  imports Query
begin

section \<open>Restricted read-only Cypher AST\<close>

text \<open>
  This AST is the final target artifact of the formal compiler.  It models only
  the read-only Cypher fragment generated by this development.  Keeping an AST
  rather than a raw string makes target syntax well formed by construction.

  A later pretty-printer may serialize this AST to concrete Neo4j Cypher text;
  that printer does not redo OCL name resolution, typing, or graph-direction
  decisions.
\<close>

datatype cy_traversal = CyOut | CyIn

record cy_nav =
  cy_rel_type     :: relationship_type
  cy_direction    :: cy_traversal
  cy_target_label :: graph_label
  cy_kind         :: collection_kind


datatype cy_expr =
    CyBool bool
  | CyInt int
  | CyReal real
  | CyString string
  | CySelf
  | CyVar vname
  | CyLet vname cy_expr cy_expr
  | CyCase cy_expr cy_expr cy_expr
  | CyProperty cy_expr property_key
  | CyNavOne cy_expr cy_nav
  | CyNavMany cy_expr cy_nav
  | CyScan graph_label
  | CyUnary ocl_unop cy_expr
  | CyBinary ocl_binop cy_expr cy_expr
  | CyFilter cy_expr vname cy_expr
  | CyCollect cy_expr vname cy_expr
  | CyForAll3 cy_expr vname cy_expr
  | CyExists3 cy_expr vname cy_expr

record cypher_query =
  cy_query_name      :: inv_name
  cy_self_variable   :: vname
  cy_context_label   :: graph_label
  cy_predicate       :: cy_expr
  cy_keep_non_true   :: bool
  cy_return_id_key   :: property_key
  cy_return_distinct :: bool


section \<open>Q to Cypher realization\<close>

fun realize_direction :: "traversal_direction \<Rightarrow> cy_traversal" where
  "realize_direction TraverseOut = CyOut"
| "realize_direction TraverseIn = CyIn"


definition realize_nav :: "query_nav \<Rightarrow> cy_nav" where
  "realize_nav n =
     \<lparr> cy_rel_type = qn_relationship_type n,
       cy_direction = realize_direction (qn_traversal n),
       cy_target_label = qn_target_label n,
       cy_kind = qn_collection_kind n
     \<rparr>"

fun realize_expr :: "q_expr \<Rightarrow> cy_expr" where
  "realize_expr (QBool b) = CyBool b"
| "realize_expr (QInt i) = CyInt i"
| "realize_expr (QReal r) = CyReal r"
| "realize_expr (QString s) = CyString s"
| "realize_expr QSelf = CySelf"
| "realize_expr (QVar x) = CyVar x"
| "realize_expr (QLet x e b) = CyLet x (realize_expr e) (realize_expr b)"
| "realize_expr (QIf c t e) = CyCase (realize_expr c) (realize_expr t) (realize_expr e)"
| "realize_expr (QProperty e k) = CyProperty (realize_expr e) k"
| "realize_expr (QNavOne e n) = CyNavOne (realize_expr e) (realize_nav n)"
| "realize_expr (QNavMany e n) = CyNavMany (realize_expr e) (realize_nav n)"
| "realize_expr (QScan l) = CyScan l"
| "realize_expr (QUnary op e) = CyUnary op (realize_expr e)"
| "realize_expr (QBinary op a b) = CyBinary op (realize_expr a) (realize_expr b)"
| "realize_expr (QFilter src x b) = CyFilter (realize_expr src) x (realize_expr b)"
| "realize_expr (QCollect src x b) = CyCollect (realize_expr src) x (realize_expr b)"
| "realize_expr (QForAll3 src x b) = CyForAll3 (realize_expr src) x (realize_expr b)"
| "realize_expr (QExists3 src x b) = CyExists3 (realize_expr src) x (realize_expr b)"


definition realize_query :: "graph_query \<Rightarrow> cypher_query" where
  "realize_query q =
     \<lparr> cy_query_name = query_name q,
       cy_self_variable = ''self'',
       cy_context_label = query_context_label q,
       cy_predicate = realize_expr (query_predicate q),
       cy_keep_non_true = True,
       cy_return_id_key = query_return_id_key q,
       cy_return_distinct = True
     \<rparr>"

text \<open>
  cy_keep_non_true=True means the generated validation query retains a context
  object whenever the invariant result is not True.  This represents the
  violation observation used by the method, rather than treating undefined as
  success.  cy_return_distinct=True expresses stable-ID projection as a set.
\<close>


section \<open>Realization equations\<close>

lemma realize_query_name[simp]:
  "cy_query_name (realize_query q) = query_name q"
  unfolding realize_query_def by simp

lemma realize_query_context[simp]:
  "cy_context_label (realize_query q) = query_context_label q"
  unfolding realize_query_def by simp

lemma realize_query_id_key[simp]:
  "cy_return_id_key (realize_query q) = query_return_id_key q"
  unfolding realize_query_def by simp

lemma realize_query_keeps_non_true[simp]:
  "cy_keep_non_true (realize_query q)"
  unfolding realize_query_def by simp

lemma realize_query_returns_distinct[simp]:
  "cy_return_distinct (realize_query q)"
  unfolding realize_query_def by simp

end
